# Generated by Django 3.0.2 on 2020-01-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(help_text='Please enter your name', max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Please enter your name', max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RE', 'Requested'), ('AC', 'Accepted'), ('DO', 'Done')], default='DO', help_text='Select your operation to view your user in that status', max_length=2)),
                ('driver', models.ForeignKey(help_text='Select the Driver', on_delete=django.db.models.deletion.CASCADE, to='CabAllocationApp.DriverModel')),
                ('user', models.ForeignKey(help_text='Select the User', on_delete=django.db.models.deletion.CASCADE, to='CabAllocationApp.UserModel')),
            ],
        ),
    ]
