# Generated by Django 3.0.2 on 2020-01-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CabAllocationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedetailsmodel',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Select the Driver', null=True, on_delete=django.db.models.deletion.CASCADE, to='CabAllocationApp.DriverModel'),
        ),
    ]
